name: Setup Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x setup.sh

      - name: Run setup script
        run: ./setup.sh
