name: Setup Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Download setup script from GitHub
        run: wget https://raw.githubusercontent.com/charukaruhub/saif-desk-script/main/setup.sh

      - name: Make setup script executable
        run: chmod +x setup.sh

      - name: Run setup script
        run: ./setup.sh

      - name: Verify NetworkManager status
        run: |
          echo "Checking NetworkManager..."
          if ! systemctl is-active --quiet NetworkManager; then
            echo "NetworkManager is not running. Starting it now..."
            sudo systemctl start NetworkManager
          fi
          sudo systemctl status NetworkManager --no-pager