name: Setup Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Download setup script from GitHub
        run: wget https://raw.githubusercontent.com/charukaruhub/saif-desk-script/main/setup.sh

      - name: Make setup script executable
        run: chmod +x setup.sh

      - name: Run setup script
        run: ./setup.sh

      - name: Check NetworkManager installation
        run: |
          if command -v nmcli &> /dev/null; then
            echo "NetworkManager installed successfully."
          else
            echo "NetworkManager installation failed."
          fi
